// Copies the canonical design tokens into each shell so every shell is
// self-contained (degit-able). Edit the SOURCE, then run `pnpm sync:tokens`.
import { readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const source = join(root, "packages/design/src/theme.css");

const targets = [
  "apps/dashboard/app/theme.css",
  "apps/app/src/theme.css",
  "apps/landing/src/styles/theme.css",
  // NOTE: apps/gastro is intentionally NOT synced — it carries its own branded
  // palette (Bodegón cálido). Re-brand per client in apps/gastro/src/styles/theme.css.
];

const banner =
  "/* AUTO-GENERATED by `pnpm sync:tokens` — do not edit.\n" +
  "   Source of truth: packages/design/src/theme.css */\n\n";

const css = readFileSync(source, "utf8");

for (const target of targets) {
  writeFileSync(join(root, target), banner + css);
  console.log("synced →", target);
}
